### ISSUE TITLE
OS X ezQuake vers out of date

### ISSUE THREAD

**Issue by amatecha** [nQuake/nquake.github.io#1]
Hi there,

I had [filed a bug with ezQuake](https://github.com/ezQuake/ezquake-source/issues/103) regarding "Growl" dependency and it turns out the version of ezQuake you're distributing with nQuake is very out of date.  As a result, many ppl who try to use nQuake on OS X won't be able to run it.  Newer versions of ezQuake resolve the problem.  This just a friendly nudge to update the ezQuake version when you have a chance.  Hope this github repo is actually looked at!  :)

**Comment by fzwoch** [comment]
Unfortunately we cant't be everywhere at once :[

From what I understood the current maintainer of "nQuake" is "mushi". Would be awesome if at some point "nQuake" would finally switch to ezQuake 3.x. Maybe "motivate" him on IRC and Discord? ;-)

**Comment by niclaslindstedt** [comment]
ezQuake 3 will be added very soon to nQuake

**Comment by amatecha** [comment]
Great news!  Cheers :) :beers:
