### ISSUE TITLE
New mirror in USA

### ISSUE THREAD

**Issue by cv1000b** [nQuake/nquake.github.io#17]
Hi,

It looked like there's no available mirrors in the USA at the moment, so I went ahead and created one:

URL: https://dallas.oystermalm.se/nquake/
Upload speed: 1 Gbit/s shared - https://www.speedtest.net/result/10430909354.png
Location: Dallas, United States

Cheers!

**Comment by eb** [comment]
Great! Comes at a great time, since the US scene has become quite active again lately.
I've added the new mirror to the list. Thanks!

**Comment by eb** [comment]
Hey @cv1000b, it seems that your mirrors are not updating. Both oystermalm.se and dallas.oystermalm.se are outdated.
That's a problem, because people get outdated binaries that crash.

All the other mirrors are doing an hourly mirror, so, would be good if you could do an hourly update as well.
Let me know if you can arrange that. Cheers!

**Comment by cv1000b** [comment]
Hi @eb 

Sorry for the trouble. I had whitelisted the IP adress of rsync.nquake.com in the firewall, but that IP seems to have changed since then, so the crontab failed because of that. Instead I have now whitelisted the hostname, so if the IP of the rsync server changes again it should be updated automatically in the CSF firewall.

Both mirrors should now be up to date, and hopefully this won't happen again.

**Comment by eb** [comment]
Great, thx! All up to date.
I don't really know about the IP change. It might be that empezar changed servers.

**Comment by eb** [comment]
Hey @cv1000b, we switched now permanently to GitHub releases as our only mirror. You can actually retire the two oystermalm mirrors. Thanks for having provided the mirrors!

**Comment by cv1000b** [comment]
Thanks. Cheers!
