### ISSUE TITLE
quakephil mirror is back :)

### ISSUE THREAD

**Issue by QuakePhil** [nQuake/nquake.github.io#7]
url for credit: http://quakephil.com
mirror path: http://52.0.31.38:8080 
upload speed: 800-600 Mbit/s**
location: us-east

** used [this](https://askubuntu.com/questions/104755/how-to-check-internet-speed-via-terminal) to test speed:
```
curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
```

**Comment by liback** [comment]
Added to installer and site, apologies for the delay and thanks for hosting! :>
