### ISSUE TITLE
New mirror

### ISSUE THREAD

**Issue by cv1000b** [nQuake/nquake.github.io#9]
Hi,

Had some free space on one my servers, and thought it would be nice to contribute to the community with a mirror. Thanks for nQuake, it's awesome!

**Mirror information:**
URL: http://oystermalm.se/nquake
Upload speed (e.g. 100 mbit/s): 1 Gbit/s shared upload (https://i.imgur.com/hbuyqPq.png)
Location (city, country): Helsinki, Finland

**Comment by liback** [comment]
Hi, apologies for the late reply, is the mirror still up? Seems i can't access the URL above (at least not via web browser)

**Comment by cv1000b** [comment]
Hi,

Yes, mirror is still up, but directory listing is not allowed. Do I need to activate that?

Files can be reached it seems, for example: http://oystermalm.se/nquake/textures.zip

Cheers!

**Comment by liback** [comment]
Mirror has finally been added, sorry for taking so long. Verified that it works to make a download and install from it too.

Many thanks for hosting and wish you a great Quake year further. :)

**Comment by cv1000b** [comment]
@liback 

I noticed my mirror was not using any bandwidth for the latest month or two, and saw that it was removed from the installer. Will it be added again, or should I remove the files? Cheers!

**Comment by liback** [comment]
Hi, the reason it was removed is because the DNS doesn't resolve anymore? I.e. http://oyestermalm.se :)

Edit: i should of course have checked with you though to see what's up, sorry for that.

**Comment by cv1000b** [comment]
Oh. It should be oystermalm.se, not oyestermalm! :)

**Comment by liback** [comment]
Ah that was my own typo, when it was added it had the correct URL but wouldn't respond (https://github.com/nQuake/client-win32/commit/d2f3b0b17f4fc9441ac9761fcba8948e29a72471)

I tested it successfully now though so will add it back in.

**Comment by cv1000b** [comment]
Oh, that's weird. I did a server migration around two months ago, but should have been up and running both before and after. Thanks for adding it again. Cheers! 👍

**Comment by eb** [comment]
@cv1000b I just noticed that the mirror was very outdated. I suppose it didn't pull changes anymore for some reason? I removed it from the INI file for the time being. Let me know if you get it up and running again and I'll re-add it. Also, it would be great if you could enable directory listing for it while at it. This way I can more easily verify that the mirror is up-to-date. The other mirrors do all an hourly cron job to pull available updates.

**Comment by cv1000b** [comment]
@eb Hi. Sorry. It seems like the rsync mirror was not whitelisted in the firewall, so it had not synced properly for a very long time. I have fixed it now, and also enabled directory listing. It's doing an hourly sync now and should continue to do so. Sorry for the trouble.

**Comment by eb** [comment]
@cv1000b Thanks! Also for the directory listing... works all very well. I've added it back to the list of mirrors.

**Comment by cv1000b** [comment]
@eb Great, thank you very much. And sorry for the trouble! :)
